### ISSUE TITLE
How to resolve the problem about the  pthreadpool in windows?

### ISSUE THREAD

**Issue by FreeApe** [zeno40/nnpack-windows#2]
As the title said.

**Comment by zeno40** [comment]
I use the [ppl](https://msdn.microsoft.com/en-us/library/dd492418.aspx) functionality in microsoft c++ under Windows and use a standard C++14 parallel_for implementation from [tiny dnn](https://github.com/tiny-dnn/tiny-dnn/blob/master/tiny_dnn/util/parallel_for.h) under Linux/ios/...
