### ISSUE TITLE
error when i use mfc visual c++

### ISSUE THREAD

**Issue by baoson202** [zeno40/nnpack-windows#3]
i can build and use it in console application but not in mfc . it is error ,about size_t , I am beginner. Please explain me ! 
thank !

**Comment by zeno40** [comment]
Can you be a bit more comprehensive and I will try to be of any help

**Comment by baoson202** [comment]
I have built nnpack lib successful.  I created project win32 application and import nnpack lib ,include "nnpack.h" , it compile successful, but when i created project mfc dialog and import lib and include "nnpack.h", it compile failed. error variable "size_t" is not a typename
![image](https://user-images.githubusercontent.com/11453117/33532513-e0323cfe-d8cc-11e7-9371-05e0c1fff44c.png)

**Comment by zeno40** [comment]
This error you encounter is not your fault. I've just  pushed a fix update in the repo. It is because in debug build min and max are not properly defined. You should try it again with the latest code.
