### ISSUE TITLE
Error On Error

### ISSUE THREAD

**Issue by Voskrese** [zeno40/nnpack-windows#4]
Tried to collect, but nothing goes, your local paths are everywhere spelled out
Compile errors

Can you lay out the prebuild?

https://github.com/zeno40/nnpack-windows/releases

**Comment by zeno40** [comment]
Hi,

I just downloaded the repo and there are indeed still wrong local path's used. Also clog is apparently missing. I will rectify this situation ASAP (a few hours)

thanks

**Comment by zeno40** [comment]
I rectified the problems with local path's and clog missing. Should build fine now
with the provided vs2017 solution. If you encounter no more problems I will issue 
a release.

**Comment by Voskrese** [comment]
```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppBuild.targets(1017
,5): error MSB3191: Не удается создать каталог "C:\Users\dhaen\Source\Repos\nnpack-windows\cpuinfo\CMakeFiles\". Отказа
но в доступе по пути "C:\Users\dhaen\Source\Repos\nnpack-windows\cpuinfo\CMakeFiles\". [E:\tools\vcpkg\buildtrees\nnpac
k-windows\cpuinfo\cpuinfo.vcxproj]
```

C:\**Users\dhaen\Source\Repos**\

**Comment by zeno40** [comment]
After you've downloaded and extracted the repo and has opened it in vs2017 you must first change your platform to x64 from the default Itanium. After that you can build the project.

**Comment by zeno40** [comment]
After you've downloaded and extracted the repo and has opened it in vs2017 you must first change your platform to x64 from the default Itanium. After that you can build the project.

(Sorry I accidently closed this)

**Comment by zeno40** [comment]
I've cleaned-up some ugly leftovers in cpuinfo and some other places. 
You should check if things are ok now.

thanks

**Comment by Voskrese** [comment]
build ok

edit `nnpack-windows\src\x86_64-fma\buildRelease.bat` `buildDebug.bat`

I have Python installed in a different place

`set python_dir=C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\`
to
`set python_dir=E:\Anaconda3\`

**Comment by zeno40** [comment]
Have you installed PeachPy?

pip install --upgrade git+https://github.com/Maratyszcza/PeachPy

**Comment by Voskrese** [comment]
yes

`"E:\Anaconda3\python.exe" -m pip install --upgrade git+https://github.com/Maratyszcza/PeachPy`

> 
> Collecting git+https://github.com/Maratyszcza/PeachPy
>   Cloning https://github.com/Maratyszcza/PeachPy to c:\temp\pip-req-build-67zmq58h
> Requirement already satisfied, skipping upgrade: six in e:\anaconda3\lib\site-packages (from PeachPy==0.2.0) (1.11.0)
> Requirement already satisfied, skipping upgrade: enum34 in e:\anaconda3\lib\site-packages (from PeachPy==0.2.0) (1.1.6)
> Installing collected packages: PeachPy
>   Found existing installation: PeachPy 0.2.0
>     Uninstalling PeachPy-0.2.0:
>       Successfully uninstalled PeachPy-0.2.0
>   Running setup.py install for PeachPy ... done
> Successfully installed PeachPy-0.2.0

All well, the compilation was successful

**thx!**
